const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const path = require('path');
const { publicLimiter, adminLimiter } = require('./middlewares/rateLimit');
const adminRoutes = require('./routes/adminRoutes');
const publicRoutes = require('./routes/publicRoutes');

const app = express();

app.disable('x-powered-by');
app.set('trust proxy', 1);

app.use(helmet());

const allowedOrigins = (process.env.CORS_ORIGIN || '')
  .split(',')
  .map((o) => o.trim())
  .filter(Boolean);

app.use(cors({
  origin: allowedOrigins.length ? allowedOrigins : false,
  methods: ['GET', 'POST', 'PUT'],
}));

app.use(express.json({ limit: '2mb' }));

// Serve audio files generated by TTS
app.use('/public/audio', express.static(path.join(__dirname, 'tmp')));

// API Routes
app.use('/api/admin', adminLimiter, adminRoutes);
app.use('/api/public', publicLimiter, publicRoutes);

// Health Check
app.get('/', (req, res) => {
  res.send('Personal AI Assistant Backend is running');
});

// 404 handler
app.use((req, res) => {
  res.status(404).json({ error: 'Not found' });
});

// Central error handler (catches malformed JSON, multer errors, etc.)
app.use((err, req, res, next) => {
  console.error('Unhandled error:', err);
  if (err.type === 'entity.too.large') {
    return res.status(413).json({ error: 'Request body too large' });
  }
  if (err.code === 'LIMIT_FILE_SIZE') {
    return res.status(413).json({ error: 'File too large' });
  }
  res.status(err.status || 500).json({ error: 'Internal server error' });
});

module.exports = app;
