const express = require('express');
const cors = require('cors');
const path = require('path');   // ✅ REQUIRED IMPORT
const adminRoutes = require('./routes/adminRoutes');
const publicRoutes = require('./routes/publicRoutes');

const app = express();

app.use(cors());
app.use(express.json());

// Serve audio files generated by TTS
app.use('/public/audio', express.static(path.join(__dirname, 'tmp')));

// API Routes
app.use('/admin', adminRoutes);
app.use('/public', publicRoutes);

// Health Check
app.get('/', (req, res) => {
  res.send('Personal AI Assistant Backend is running');
});

module.exports = app;
